# Generated by Django 3.2.7 on 2021-09-06 01:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_customuser_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='Puzzle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('date', models.DateField()),
                ('given_digits', models.CharField(max_length=81)),
                ('cell_colors', models.CharField(max_length=81)),
                ('average_solve_time', models.TimeField()),
                ('completed', models.BooleanField()),
                ('rule_set', models.TextField()),
                ('average_rating', models.FloatField()),
                ('diagonals', models.IntegerField()),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
