# Generated by Django 3.2.7 on 2021-09-06 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_puzzle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puzzle',
            name='average_rating',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='puzzle',
            name='average_solve_time',
            field=models.TimeField(blank=True),
        ),
    ]
