# Generated by Django 3.2.7 on 2021-09-16 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20210905_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puzzle',
            name='average_solve_time',
            field=models.TimeField(blank=True),
        ),
    ]
