# Generated by Django 3.2.7 on 2021-09-17 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_alter_puzzle_average_solve_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='puzzle',
            name='solution_digits',
            field=models.CharField(default='_________________________________________________________________________________', max_length=81),
            preserve_default=False,
        ),
    ]
